root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "templ generate && go build -o ./tmp/main ."
delay = 0
exclude_dir = ["tmp", "docs", "configs", "build"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js", "jpg", "jpeg", "svg"]
include_file = ["main.go"]
kill_delay = "0s"
log = "build-errors.log"
pre_cmd = ["echo starting build"]
post_cmd = ["echo build completed"]
poll = false
poll_interval = 0
rerun = false
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
