// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/HielkeFellinger/dramatic_gopher/app/engine"
	"github.com/HielkeFellinger/dramatic_gopher/app/models"
	"github.com/HielkeFellinger/dramatic_gopher/app/views/components"
)

func Session(user models.User, game engine.Game) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body class=\"bg-gray-800\"><main class=\"min-h-screen min-h-screen min-w-screen\"><div class=\"container flex flex-row justify-center items-center min-h-screen min-w-screen\" hx-ext=\"ws\" ws-connect=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("/session/" + game.GetId() + "/ws")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/session.templ`, Line: 15, Col: 166}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><div id=\"chat_screen\" class=\"min-w-112 max-w-112 min-h-screen max-h-screen border-r border-gray-700 border-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.FullChat().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><div id=\"main_screen\" class=\"flex min-h-screen flex-grow\"><h4 class=\"font-bold text-gray-200\"><span id=\"status\"></span> Game : '")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(game.GetId())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/session.templ`, Line: 20, Col: 108}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "'</h4></div><div id=\"detail_screen\" class=\"min-w-128 min-h-screen border-l border-gray-700 border-1 items-center justify-between\">DETAILS</div></div></main></body></html><script type=\"text/javascript\" defer>\n        if (lucide) {\n            lucide.createIcons();\n        }\n\n        let reconnectTimer = 0;\n        let status = document.getElementById('status');\n        let socket;\n        let elt;\n\n        document.body.addEventListener('htmx:wsConnecting', function (evt) {\n            console.log('connecting to server');\n            status.innerText = 'Connecting to ';\n\n            // @TODO Implement incremental back-off\n\n            status.classList.add('text-orange-700')\n            status.classList.remove('text-red-700')\n            status.classList.remove('text-green-700')\n            status.setAttribute('data-status', 'connecting');\n        });\n        document.body.addEventListener('htmx:wsOpen', function(evt) {\n            console.log('connected');\n            reconnectTimer = 0;\n            socket = evt.detail.socketWrapper;\n            elt = evt.detail.elt;\n\n            status.innerText = 'Connected to ';\n            status.classList.add('text-green-700')\n            status.classList.remove('text-red-700')\n            status.classList.remove('text-orange-700')\n            status.setAttribute('data-status', 'connected');\n        });\n        document.body.addEventListener('htmx:wsClose', function(evt) {\n            console.log('disconnected');\n            console.warn(evt.detail)\n            reconnectTimer++;\n\n            if (reconnectTimer > 5) {\n                window.location = \"/game/join/")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4, templ_7745c5c3_Err := templruntime.ScriptContentInsideStringLiteral(game.GetId())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/views/session.templ`, Line: 68, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"\n            }\n\n            status.innerText = 'Disconnected from ';\n            status.classList.add('text-red-700')\n            status.classList.remove('text-orange-700')\n            status.classList.remove('text-green-700')\n            status.setAttribute('data-status', 'disconnected');\n        });\n\n        function reAuthUserToGame(gameId) {\n\n        }\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
